using JogoDaForcaApp.Models;

namespace JogoDaForcaApp.Repositories;

public class WordRepository
{
    private readonly List<Word> _words;

    public WordRepository()
    {
        _words =
        [
            // Nomes
            new("Nome", "ADRIANA"),
            new("Nome", "ALBERTO"),
            new("Nome", "ALICE"),
            new("Nome", "ANA"),
            new("Nome", "ANDRE"),
            new("Nome", "ANTONIO"),
            new("Nome", "BEATRIZ"),
            new("Nome", "BRUNO"),
            new("Nome", "CARLOS"),
            new("Nome", "CECILIA"),
            new("Nome", "CLARA"),
            new("Nome", "CRISTINA"),
            new("Nome", "DANIEL"),
            new("Nome", "DANIELLE"),
            new("Nome", "EDUARDO"),
            new("Nome", "FERNANDA"),
            new("Nome", "FELIPE"),
            new("Nome", "FRANCISCO"),
            new("Nome", "GABRIEL"),
            new("Nome", "GABRIELA"),
            new("Nome", "GUILHERME"),
            new("Nome", "GUSTAVO"),
            new("Nome", "HELOISA"),
            new("Nome", "HENRIQUE"),
            new("Nome", "ISABELLA"),
            new("Nome", "ISADORA"),
            new("Nome", "JOANA"),
            new("Nome", "JOAO"),
            new("Nome", "JULIA"),
            new("Nome", "JULIANA"),
            new("Nome", "LEONARDO"),
            new("Nome", "LETICIA"),
            new("Nome", "LUCAS"),
            new("Nome", "LUCIANO"),
            new("Nome", "LUIS"),
            new("Nome", "MARCELA"),
            new("Nome", "MARCOS"),
            new("Nome", "MARA"),
            new("Nome", "MARIA"),
            new("Nome", "MARIANA"),
            new("Nome", "MARCIA"),
            new("Nome", "MIGUEL"),
            new("Nome", "NATHALIA"),
            new("Nome", "PEDRO"),
            new("Nome", "RAFAEL"),
            new("Nome", "RAFAELA"),
            new("Nome", "RENATA"),
            new("Nome", "RICARDO"),
            new("Nome", "ROBERTO"),
            new("Nome", "RODRIGO"),
            new("Nome", "SABRINA"),
            new("Nome", "SANDRA"),
            new("Nome", "SILVIA"),
            new("Nome", "THAIS"),
            new("Nome", "TIAGO"),
            new("Nome", "VICTOR"),
            new("Nome", "VIVIANE"),
            new("Nome", "YASMIN"),


            // Vegetais
            new("Vegetal", "BETERRABA"),
            new("Vegetal", "BROCOLIS"),
            new("Vegetal", "CENOURA"),
            new("Vegetal", "COUVE"),
            new("Vegetal", "ESPINAFRE"),
            new("Vegetal", "ALFACE"),
            new("Vegetal", "ABOBRINHA"),
            new("Vegetal", "AGRIAO"),
            new("Vegetal", "ALHO"),
            new("Vegetal", "BATATA"),
            new("Vegetal", "BERINJELA"),
            new("Vegetal", "MILHO"),
            new("Vegetal", "CARAMBOLA"),
            new("Vegetal", "JILO"),
            new("Vegetal", "MANDIOCA"),
            new("Vegetal", "MEXILHAO"),
            new("Vegetal", "MILHO"),
            new("Vegetal", "NABO"),
            new("Vegetal", "PIMENTAO"),
            new("Vegetal", "QUIABO"),
            new("Vegetal", "RUCULA"),
            new("Vegetal", "SALSÃO"),
            new("Vegetal", "TOMATE"),


            // Frutas
            new("Fruta", "ABACATE"),
            new("Fruta", "BANANA"),
            new("Fruta", "LARANJA"),
            new("Fruta", "MORANGO"),
            new("Fruta", "MACA"),
            new("Fruta", "MANGA"),
            new("Fruta", "MELANCIA"),
            new("Fruta", "PERA"),
            new("Fruta", "PESSEGO"),
            new("Fruta", "UVA"),
            new("Fruta", "AMORA"),
            new("Fruta", "CAJU"),
            new("Fruta", "CARAMBOLA"),
            new("Fruta", "CUPUACU"),
            new("Fruta", "FIGO"),
            new("Fruta", "GRAVIOLA"),
            new("Fruta", "JACA"),
            new("Fruta", "KIWI"),
            new("Fruta", "LIMAO"),
            new("Fruta", "MEXERICA"),
            new("Fruta", "NABO"),
            new("Fruta", "NECTARINA"),
            new("Fruta", "PAPAIA"),
            new("Fruta", "PITANGA"),
            new("Fruta", "ROMA"),
            new("Fruta", "TANGERINA"),

            // Temperos
            new("Tempero", "ALECRIM"),
            new("Tempero", "OREGANO"),
            new("Tempero", "SALSA"),
            new("Tempero", "ALHO"),
            new("Tempero", "CEBOLA"),
            new("Tempero", "COENTRO"),
            new("Tempero", "MANJERICAO"),
            new("Tempero", "PIMENTA"),
            new("Tempero", "PAPRICA"),
            new("Tempero", "CANELA"),

            // Animais
            new("Animal", "CACHORRO"),
            new("Animal", "CAVALO"),
            new("Animal", "COELHO"),
            new("Animal", "ELEFANTE"),
            new("Animal", "GATO"),
            new("Animal", "TIGRE"),
            new("Animal", "LEAO"),
            new("Animal", "URSO"),
            new("Animal", "AVESTRUZ"),
            new("Animal", "COELHO"),
            new("Animal", "MACACO"),
            new("Animal", "PAVAO"),
            new("Animal", "PUMA"),
            new("Animal", "ONCA"),
            new("Animal", "GIRAFA"),
            new("Animal", "ZEBRA"),

            // Países
            new("País", "ARGENTINA"),
            new("País", "BRASIL"),
            new("País", "ESPANHA"),
            new("País", "FRANCA"),
            new("País", "JAPAO"),
            new("País", "ALEMANHA"),
            new("País", "INGLATERRA"),
            new("País", "ITALIA"),
            new("País", "CANADA"),
            new("País", "MEXICO"),
            new("País", "AUSTRALIA"),
            new("País", "PORTUGAL"),
            new("País", "RUSSIA"),
            new("País", "CHINA"),
            new("País", "INDIA"),

            // Cores
            new("Cor", "AZUL"),
            new("Cor", "AMARELO"),
            new("Cor", "ROXO"),
            new("Cor", "VERDE"),
            new("Cor", "VERMELHO"),
            new("Cor", "LARANJA"),
            new("Cor", "PRETO"),
            new("Cor", "BRANCO"),
            new("Cor", "CINZA"),
            new("Cor", "BEGE"),
            new("Cor", "MARROM"),
            new("Cor", "ROSADO"),
            new("Cor", "DOURADO"),
            new("Cor", "PRATA"),

            // Cidades
            new("Cidade", "LONDRES"),
            new("Cidade", "PARIS"),
            new("Cidade", "TOKIO"),
            new("Cidade", "LISBOA"),
            new("Cidade", "ROMA"),
            new("Cidade", "MADRI"),
            new("Cidade", "LISBOA"),
            new("Cidade", "MIAMI"),
            new("Cidade", "AMSTERDAM"),
            new("Cidade", "BERLIM"),
            new("Cidade", "MUNIQUE"),
            new("Cidade", "BARCELONA"),

            // Objetos
            new("Objeto", "CADEIRA"),
            new("Objeto", "CADERNO"),
            new("Objeto", "LAPIS"),
            new("Objeto", "MESA"),
            new("Objeto", "RELOGIO"),
            new("Objeto", "FONE"),
            new("Objeto", "TELEFONE"),
            new("Objeto", "BOLSA"),
            new("Objeto", "CANETA"),
            new("Objeto", "GUITARRA"),
            new("Objeto", "LIVRO"),

            // Alimentos
            new("Alimento", "ARROZ"),
            new("Alimento", "CHOCOLATE"),
            new("Alimento", "FEIJAO"),
            new("Alimento", "PAO"),
            new("Alimento", "PIZZA"),
            new("Alimento", "MASSA"),
            new("Alimento", "SALADA"),
            new("Alimento", "SOPA"),
            new("Alimento", "FRANGO"),
            new("Alimento", "CARNE"),
            new("Alimento", "PEIXE"),
            new("Alimento", "OVO"),
            new("Alimento", "BATATA"),
            new("Alimento", "MACA"),
            new("Alimento", "LIMAO"),

            // Profissões
            new("Profissão", "ADVOGADO"),
            new("Profissão", "ARQUITETO"),
            new("Profissão", "ENGENHEIRO"),
            new("Profissão", "MEDICO"),
            new("Profissão", "PROFESSOR"),
            new("Profissão", "ENFERMEIRO"),
            new("Profissão", "PSICOLOGO"),
            new("Profissão", "DENTISTA"),
            new("Profissão", "FARMACEUTICO"),
            new("Profissão", "COSTUREIRO"),
            new("Profissão", "JORNALISTA"),
            new("Profissão", "DESENVOLVEDOR"),
            new("Profissão", "ARQUITETA"),
            new("Profissão", "BIOLOGO"),
            new("Profissão", "PROGRAMADOR"),
        ];
    }

    public Word GetRandomWord()
    {
        Random rand = new();
        var number = rand.Next(0, _words.Count);
        return _words[number];
    }
}
